server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8083

spring:
  redis:
    database: 5
    # 配置redis的主机地址，需要修改成自己的
    host: localhost
    port: 6379
    timeout: 5000
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 500
        # 连接池中的最小空闲连接，默认值也是0。
        min-idle: 50
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 1000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 2000
  activemq:
    # activemq url
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
        # 如果此处设置为true，需要添加activemq-pool的依赖包，否则会自动配置失败，无法注入JmsMessagingTemplate
        enabled: false

logging:
  config: logback-spring.xml
  level:
    com.itcodai.course03.dao: trace
# 配置微服务的地址
url:
  # 订单微服务的地址
  orderUrl: http://localhost:8005
  # 用户微服务的地址
  userUrl: http://localhost:8006
  # 购物车微服务的地址
  shoppingUrl: http://localhost:8007
